//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebSite
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ProductTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string QuantityAvail { get; set; }
        public string imagesrc { get; set; }
        public string Category { get; set; }
        public IEnumerable<SelectListItem> Quantity { get; set; }
        public int StaticQuantity { get; set; }

        public string StaticPrice { get; set; }

    }
}
